version: '3.3'
services:
  env:
    image: tghastings/code-esaas
    container_name: env
    restart: always
    ports:
      - 80:80
      - 3000:3000
    volumes:
      - data:/root/environment/
    networks:
      - rubynet
 
  pg:
    container_name: pg
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password1234!
    volumes:
      - pg:/root/environment/pg
    networks:
      - rubynet

  adminer:
    container_name: db_ui
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - adminer:/root/environment/adminer
    networks:
      - rubynet

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    depends_on: 
      - pg
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pt@domain.com
      PGADMIN_DEFAULT_PASSWORD: password1234!
    restart: always
    volumes:
      - pgAdmin:/root/environment/pgAdmin
    networks:
      - rubynet

volumes:
  data:
  pg:
  pgAdmin:
  adminer:

networks:
  rubynet: